feat: new GTF to RSeQC bed12 format script
stjudecloud/utilities pull request #3
Opened 2021-01-25 17:24 UTC by a-frantz

2021-01-25 18:40 UTC, adthrasher requested changes
Could you add some documentation and help info? Also add to the README to describe the script and briefly its uses.

2021-01-26 00:47 UTC, claymcleod commented
IMO, we should be using argparse at minimum here.

2021-02-01 15:43 UTC, a-frantz commented
@adthrasher implemented suggestions

2021-02-01 19:32 UTC, adthrasher approved these changes

2021-02-01 20:21 UTC, merged